import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AuthFacade } from '../../application/auth.facade';
import { I18nService } from '../../../core/i18n/i18n.service';

@Component({standalone:true,imports:[ReactiveFormsModule,RouterLink,MatButtonModule,MatFormFieldModule,MatInputModule,MatIconModule,MatSnackBarModule],template:`
<div class="register-wrap"><div class="register-card panel"><a routerLink="/login" class="back">← {{i18n.t('common.back')}}</a><div class="brand"><span>A</span><strong>AgroLeak</strong></div><h1>{{i18n.t('auth.createAccount')}}</h1><p>{{i18n.t('auth.registerHint')}}</p>
<form [formGroup]="form" (ngSubmit)="submit()"><div class="form-grid"><mat-form-field appearance="outline"><mat-label>{{i18n.t('auth.firstName')}}</mat-label><input matInput formControlName="firstName"></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i18n.t('auth.lastName')}}</mat-label><input matInput formControlName="lastName"></mat-form-field><mat-form-field appearance="outline" class="full"><mat-label>Email</mat-label><input matInput type="email" formControlName="email"></mat-form-field><mat-form-field appearance="outline" class="full"><mat-label>{{i18n.t('auth.password')}}</mat-label><input matInput type="password" formControlName="password"><mat-hint>8+ caracteres</mat-hint></mat-form-field></div>@if(error()){<div class="error">{{error()}}</div>}<button mat-flat-button color="primary" class="submit" [disabled]="form.invalid||loading()">{{i18n.t('auth.register')}}</button></form>
<p class="switch">{{i18n.t('auth.hasAccount')}} <a routerLink="/login">{{i18n.t('auth.login')}}</a></p></div></div>`,styles:[`.register-wrap{min-height:100vh;display:grid;place-items:center;padding:32px;background:radial-gradient(circle at top left,#dfeeda,transparent 38%),var(--ag-bg)}.register-card{width:min(620px,100%);padding:36px}.back{color:var(--ag-muted);font-size:.84rem}.brand{display:flex;align-items:center;gap:10px;margin:26px 0 20px}.brand span{width:34px;height:34px;border-radius:10px;background:#d7f1bf;color:#0f4c3a;display:grid;place-items:center;font-weight:900}.register-card h1{font-size:2rem;letter-spacing:-.04em;margin:0}.register-card>p{color:var(--ag-muted)}form{margin-top:28px}.submit{width:100%;height:48px}.error{padding:10px;border-radius:10px;background:#fde8e8;color:#a92f2f;margin-bottom:12px}.switch{text-align:center!important;margin-top:20px!important}.switch a{color:var(--ag-primary-2);font-weight:700}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class RegisterPageComponent{readonly i18n=inject(I18nService);private fb=inject(FormBuilder);private auth=inject(AuthFacade);private router=inject(Router);private snack=inject(MatSnackBar);readonly loading=signal(false);readonly error=signal('');readonly form=this.fb.nonNullable.group({firstName:['',[Validators.required,Validators.maxLength(100)]],lastName:['',[Validators.required,Validators.maxLength(100)]],email:['',[Validators.required,Validators.email]],password:['',[Validators.required,Validators.minLength(8),Validators.maxLength(72)]]});submit(){if(this.form.invalid)return;this.loading.set(true);this.auth.register(this.form.getRawValue()).subscribe({next:()=>{this.snack.open(this.i18n.t('auth.registerSuccess'),'OK',{duration:2500});void this.router.navigate(['/login']);},error:e=>{this.loading.set(false);this.error.set(e?.error?.message||'No se pudo registrar el usuario.');}})}}
