import { ChangeDetectionStrategy,Component,inject,signal } from '@angular/core';
import { ReactiveFormsModule,FormBuilder,Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';import { MatIconModule } from '@angular/material/icon';import { MatFormFieldModule } from '@angular/material/form-field';import { MatInputModule } from '@angular/material/input';import { MatSnackBar,MatSnackBarModule } from '@angular/material/snack-bar';
import { FarmFacade } from '../../application/farm.facade';import { EmptyStateComponent } from '../../../shared/ui/empty-state.component';import { LoadingStateComponent } from '../../../shared/ui/loading-state.component';import { I18nService } from '../../../core/i18n/i18n.service';
@Component({standalone:true,imports:[ReactiveFormsModule,RouterLink,MatButtonModule,MatIconModule,MatFormFieldModule,MatInputModule,MatSnackBarModule,EmptyStateComponent,LoadingStateComponent],template:`<div class="page"><div class="page-header"><div><h1 class="page-title">{{i18n.t('farms.title')}}</h1><p class="page-subtitle">{{i18n.t('farms.subtitle')}}</p></div><button mat-flat-button color="primary" (click)="showForm.set(!showForm())"><mat-icon>add</mat-icon>{{i18n.t('farms.new')}}</button></div>
@if(showForm()){<section class="panel panel-body create"><h3>{{i18n.t('farms.new')}}</h3><form [formGroup]="form" (ngSubmit)="create()" class="form-grid"><mat-form-field appearance="outline"><mat-label>{{i18n.t('common.name')}}</mat-label><input matInput formControlName="name"></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i18n.t('common.location')}}</mat-label><input matInput formControlName="location"></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i18n.t('farms.area')}}</mat-label><input matInput type="number" formControlName="areaHectares"></mat-form-field><div class="form-actions"><button mat-flat-button color="primary" [disabled]="form.invalid">{{i18n.t('common.save')}}</button><button mat-button type="button" (click)="showForm.set(false)">{{i18n.t('common.cancel')}}</button></div></form></section>}
@if(facade.loading()){<app-loading-state/>}@else if(!facade.farms().length){<section class="panel"><app-empty-state icon="🌾" [title]="i18n.t('farms.empty')" [message]="i18n.t('farms.emptyHint')"/></section>}@else{<div class="grid grid-3 farms">@for(farm of facade.farms();track farm.id){<article class="panel farm-card"><div class="farm-cover"><mat-icon>landscape</mat-icon><span>{{farm.areaHectares}} ha</span></div><div class="farm-body"><div class="farm-head"><div><h3>{{farm.name}}</h3><p><mat-icon>location_on</mat-icon>{{farm.location}}</p></div><button mat-icon-button (click)="remove(farm.id);$event.preventDefault()"><mat-icon>delete_outline</mat-icon></button></div><a mat-stroked-button [routerLink]="['/farms',farm.id]">{{i18n.t('farms.manage')}} <mat-icon>arrow_forward</mat-icon></a></div></article>}</div>}</div>`,styles:[`.create{margin-bottom:22px}.create h3{margin-top:0}.farms{margin-top:8px}.farm-card{overflow:hidden}.farm-cover{height:132px;background:linear-gradient(135deg,#dbead2,#eef4e9);display:flex;align-items:flex-end;justify-content:space-between;padding:18px;color:#315a42}.farm-cover>mat-icon{font-size:44px;width:44px;height:44px}.farm-cover span{font-weight:800;background:rgba(255,255,255,.68);padding:6px 9px;border-radius:999px}.farm-body{padding:18px}.farm-head{display:flex;justify-content:space-between;gap:10px}.farm-head h3{margin:0;font-size:1.1rem}.farm-head p{display:flex;align-items:center;gap:4px;color:var(--ag-muted);font-size:.8rem}.farm-head p mat-icon{font-size:16px;width:16px;height:16px}.farm-body>a{width:100%;margin-top:12px}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class FarmListPageComponent{readonly facade=inject(FarmFacade);readonly i18n=inject(I18nService);private fb=inject(FormBuilder);private snack=inject(MatSnackBar);readonly showForm=signal(false);readonly form=this.fb.nonNullable.group({name:['',Validators.required],location:['',Validators.required],areaHectares:[1,[Validators.required,Validators.min(.01)]]});constructor(){this.facade.load().subscribe()}create(){if(this.form.invalid)return;this.facade.create(this.form.getRawValue()).subscribe(()=>{this.snack.open(this.i18n.t('common.saved'),'OK',{duration:1800});this.form.reset({name:'',location:'',areaHectares:1});this.showForm.set(false)})}remove(id:string){if(confirm(this.i18n.t('farms.deleteConfirm')))this.facade.delete(id).subscribe()}}
